
###
GET http://localhost:8080/movies/tt0102034
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyZGlhbm1hbGlxYWo0OUBnbWFpbC5jb20iLCJGaXJzdE5hbWUiOiJBcmRpYW4iLCJMYXN0TmFtZSI6Ik1hbGlxYWoiLCJSb2xlIjoiVVNFUiIsIlVzZXJJRCI6IjY4ZmJhN2I2MmIwOGZhZGY3Yzc2MDYwYiIsImlzcyI6IkdvdHJvY2siLCJleHAiOjE3NjE0MjMwNTQsImlhdCI6MTc2MTMzNjY1NH0.NlTl1IF12G9bkhd50x_1tGFEsgPWO9v_UUACPiB5JeA

###
GET http://localhost:8080/movies

###
GET http://localhost:8080/movies/recommanded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyZGlhbm1hbGlxYWo0OUBnbWFpbC5jb20iLCJGaXJzdE5hbWUiOiJBcmRpYW4iLCJMYXN0TmFtZSI6Ik1hbGlxYWoiLCJSb2xlIjoiVVNFUiIsIlVzZXJJRCI6IjY4ZmJhN2I2MmIwOGZhZGY3Yzc2MDYwYiIsImlzcyI6IkdvdHJvY2siLCJleHAiOjE3NjE0MjMwNTQsImlhdCI6MTc2MTMzNjY1NH0.NlTl1IF12G9bkhd50x_1tGFEsgPWO9v_UUACPiB5JeA

###
GET http://localhost:8080/movies/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyZGlhbm1hbGlxYWo0OUBnbWFpbC5jb20iLCJGaXJzdE5hbWUiOiJBcmRpYW4iLCJMYXN0TmFtZSI6Ik1hbGlxYWoiLCJSb2xlIjoiVVNFUiIsIlVzZXJJRCI6IjY4ZmJhN2I2MmIwOGZhZGY3Yzc2MDYwYiIsImlzcyI6IkdvdHJvY2siLCJleHAiOjE3NjE0MjMwNTQsImlhdCI6MTc2MTMzNjY1NH0.NlTl1IF12G9bkhd50x_1tGFEsgPWO9v_UUACPiB5JeA

### review with an admin
PATCH http://localhost:8080/movies/review/tt0109040
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFtLmFyZGlhbi5tYWxpcWFqQGdtYWlsLmNvbSIsIkZpcnN0TmFtZSI6IkFyZGlhbiIsIkxhc3ROYW1lIjoiTWFsaXFhaiIsIlJvbGUiOiJBRE1JTiIsIlVzZXJJRCI6IjY4ZmJlN2FhYzYzZjA0NzdhZWQ3NjhmZSIsImlzcyI6IkdvdHJvY2siLCJleHAiOjE3NjE0MjU3NzIsImlhdCI6MTc2MTMzOTM3Mn0.sPoXGFDHZT3ydP05vSNWLBpP29cSaX9fB6O6HovNNyM

###
POST http://localhost:8080/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyZGlhbm1hbGlxYWo0OUBnbWFpbC5jb20iLCJGaXJzdE5hbWUiOiJBcmRpYW4iLCJMYXN0TmFtZSI6Ik1hbGlxYWoiLCJSb2xlIjoiVVNFUiIsIlVzZXJJRCI6IjY4ZmJhN2I2MmIwOGZhZGY3Yzc2MDYwYiIsImlzcyI6IkdvdHJvY2siLCJleHAiOjE3NjE0MjMwNTQsImlhdCI6MTc2MTMzNjY1NH0.NlTl1IF12G9bkhd50x_1tGFEsgPWO9v_UUACPiB5JeA
Content-Type: application/json

{
    "imdb_id": "tt0102034",
    "title": "Highlander 2: The Quickening",
    "poster_path": "https://image.tmdb.org/t/p/original/gFPIgpwtnsiq6AG5HlgOzK1TNke.jpg",
    "youtube_id": "pRgJVvoihCQ",
    "genre": [
        {
            "genre_id": 6,
            "genre_name": "Sci-fi"
        },
        {
            "genre_id": 4,
            "genre_name": "Fantasy"
        }
    ],
    "admin_review": "This movie was really bad",
    "ranking": {
        "ranking_value": 4,
        "ranking_name": "bad"
    }
}

###
DELETE http://localhost:8080/movies/tt0102034
