###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "ardianmaliqaj49@gmail.com",
  "password": "gotrock73"
}

###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Ardian",
  "last_name": "Maliqaj",
  "email": "ardianmaliqaj49@gmail.com",
  "password": "gotrock73",
  "role": "USER",
  "token": "",
  "refresh_token": "",
  "favourite_genres": [
    {
      "genre_id": 1,
      "genre_name": "Comedy"
    },
    {
      "genre_id": 5,
      "genre_name": "Thriller"
    },
    {
      "genre_id": 6,
      "genre_name": "Sci-Fi"
    }
  ]
}