###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "am.ardian.maliqaj@gmail.com",
  "password": "gotrock73"
}

###
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFtLmFyZGlhbi5tYWxpcWFqQGdtYWlsLmNvbSIsIkZpcnN0TmFtZSI6IkFyZGlhbiIsIkxhc3ROYW1lIjoiTWFsaXFhaiIsIlJvbGUiOiJBRE1JTiIsIlVzZXJJRCI6IjY4ZmJlN2FhYzYzZjA0NzdhZWQ3NjhmZSIsImlzcyI6IkdvdHJvY2siLCJleHAiOjE3NjE1MDQyNjQsImlhdCI6MTc2MTQxNzg2NH0.nEabgXitJL4CSyfoteFFKwGi5YcuIzkVjiU1Dxw26gE

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Ardian",
  "last_name": "Maliqaj",
  "email": "ardianmaliqaj49@gmail.com",
  "password": "gotrock73",
  "role": "USER",
  "token": "",
  "refresh_token": "",
  "favourite_genres": [
    {
      "genre_id": 1,
      "genre_name": "Comedy"
    },
    {
      "genre_id": 5,
      "genre_name": "Thriller"
    },
    {
      "genre_id": 6,
      "genre_name": "Sci-Fi"
    }
  ]
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Ardian",
  "last_name": "Maliqaj",
  "email": "am.ardian.maliqaj@gmail.com",
  "password": "gotrock73",
  "role": "ADMIN",
  "token": "",
  "refresh_token": "",
  "favourite_genres": [
    {
      "genre_id": 1,
      "genre_name": "Comedy"
    },
    {
      "genre_id": 5,
      "genre_name": "Thriller"
    },
    {
      "genre_id": 6,
      "genre_name": "Sci-Fi"
    }
  ]
}